packageExtensions:
  "@apollo/client@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@apollo/gateway@*":
    dependencies:
      node-fetch: "*"
  "@apollo/link-error@*":
    peerDependencies:
      graphql: "*"
  "@apollo/react-hooks@*":
    dependencies:
      "@types/react": "*"
      "@types/zen-observable": "*"
      apollo-cache: "*"
      apollo-cache-inmemory: "*"
      apollo-link: "*"
      graphql: "*"
      react: "*"
  "@apollo/react-ssr@*":
    dependencies:
      react: "*"
    peerDependencies:
      graphql: "*"
  "@apollo/react-testing@*":
    dependencies:
      "@apollo/client": "*"
      "@types/react": "*"
      apollo-cache: "*"
      apollo-cache-inmemory: "*"
      apollo-client: "*"
      apollo-link: "*"
      apollo-utilities: "*"
    peerDependencies:
      graphql: "*"
  "@atls/nestjs-dataloader@*":
    dependencies:
      "@nestjs/core": "*"
    peerDependencies:
      graphql: "*"
  "@atls/next-app-with-apollo@*":
    dependencies:
      "@apollo/react-common": "*"
      "@apollo/react-ssr": "*"
      "@types/react": "*"
      "@types/zen-observable": "*"
      next: "*"
      react: "*"
      zen-observable: "*"
  "@atls/next-app-with-auth@*":
    dependencies:
      "@types/react": "*"
  "@atls/next-app-with-emotion@*":
    dependencies:
      "@types/react": "*"
      react: "*"
  "@atls/next-app-with-helmet@*":
    dependencies:
      "@types/react": "*"
      react: "*"
      react-helmet: "*"
  "@atls/next-app-with-intl@*":
    dependencies:
      "@types/react": "*"
  "@atls/next-app-with-provider@*":
    dependencies:
      "@types/react": "*"
      react: "*"
  "@atls/next-app-with-user@*":
    dependencies:
      "@types/react": "*"
  "@atls/next-document-with-emotion@*":
    dependencies:
      "@types/react": "*"
      emotion-server: "*"
      next: "*"
      react: "*"
  "@atls/next-document-with-helmet@*":
    dependencies:
      "@types/react": "*"
      next: "*"
      react: "*"
      react-helmet: "*"
  "@atls/react-locale@*":
    dependencies:
      "@types/react": "*"
  "@elastic/elasticsearch@*":
    dependencies:
      "@types/node": "*"
  "@emotion/styled@*":
    dependencies:
      "@types/react": "*"
  "@graphql-typed-document-node/core@*":
    peerDependencies:
      graphql: "*"
  "@grpc/grpc-js@*":
    dependencies:
      "@types/long": "*"
  "@grpc/proto-loader@*":
    dependencies:
      "@types/node": "*"
  "@mapbox/node-pre-gyp@*":
    dependencies:
      aws-sdk: "*"
      mock-aws-s3: "*"
      nock: "*"
  "@monstrs/nestjs-bus@*":
    dependencies:
      "@monstrs/nestjs-logger": "*"
      "@nestjs/core": "*"
      reflect-metadata: "*"
      serialize-error: "*"
  "@monstrs/nestjs-dataloader@*":
    dependencies:
      "@nestjs/core": "*"
  "@monstrs/server-scripts@*":
    dependencies:
      "@lerna/project": "*"
      cross-spawn: "*"
      serialize-error: "*"
  "@nestjs/common@*":
    dependencies:
      "@types/node": "*"
      cache-manager: "*"
      class-transformer: "*"
      class-validator: "*"
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/core@*":
    dependencies:
      "@nestjs/microservices": "*"
      "@nestjs/platform-express": "*"
      "@nestjs/platform-socket.io": "*"
      "@nestjs/websockets": "*"
      apollo-server-fastify: "*"
      iterall: "*"
      reflect-metadata: "*"
      rxjs: "*"
    peerDependencies:
      graphql: "*"
  "@nestjs/graphql@*":
    dependencies:
      "@apollo/federation": "*"
      "@apollo/gateway": "*"
      "@apollo/subgraph": "*"
      "@nestjs/common": "*"
      apollo-server-core: "*"
      apollo-server-express: "*"
      apollo-server-fastify: "*"
      class-transformer: "*"
      class-validator: "*"
      iterall: "*"
      reflect-metadata: "*"
      ts-morph: "*"
    peerDependencies:
      "@nestjs/core": "*"
      graphql: "*"
  "@nestjs/mapped-types@*":
    dependencies:
      class-transformer: "*"
  "@nestjs/microservices@*":
    dependencies:
      "@grpc/grpc-js": "*"
      "@grpc/proto-loader": "*"
      "@nestjs/common": "*"
      "@nestjs/websockets": "*"
      "@types/node": "*"
      amqp-connection-manager: "*"
      amqplib: "*"
      kafkajs: "*"
      mqtt: "*"
      nats: "*"
      redis: "*"
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/platform-socket.io@*":
    peerDependencies:
      "@nestjs/core": "*"
  "@nestjs/terminus@*":
    dependencies:
      axios: "*"
  "@nestjs/testing@*":
    dependencies:
      "@nestjs/common": "*"
      "@nestjs/core": "*"
  "@nestjs/typeorm@*":
    dependencies:
      rxjs: "*"
    peerDependencies:
      "@nestjs/core": "*"
  "@nestjs/websockets@*":
    dependencies:
      "@nestjs/platform-socket.io": "*"
      rxjs: "*"
  "@node-ts/bus-core@*":
    dependencies:
      "@node-ts/logger-core": "*"
      inversify: "*"
  "@node-ts/ddd@*":
    dependencies:
      "@node-ts/bus-core": "*"
      "@node-ts/logger-core": "*"
      inversify: "*"
      tslib: "*"
  "@node-ts/logger-core@*":
    dependencies:
      inversify: "*"
      tslib: "*"
  "@oryd/hydra-client@*":
    dependencies:
      "@types/node": "*"
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
  "@types/rc-trigger@*":
    dependencies:
      "@types/react": "*"
      react: "*"
  apollo-env@*:
    dependencies:
      "@types/node": "*"
  apollo-server-core@*:
    dependencies:
      "@types/node": "*"
    peerDependencies:
      graphql: "*"
  apollo-server-errors@*:
    peerDependencies:
      graphql: "*"
  apollo-server-express@*:
    dependencies:
      express: "*"
  argon2@*:
    dependencies:
      "@types/node": "*"
  chokidar@*:
    dependencies:
      fsevents: "*"
  component-classes@*:
    dependencies:
      indexof: "*"
  create-emotion-server@*:
    dependencies:
      "@types/node": "*"
  create-react-class@*:
    dependencies:
      react: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  emotion-server@*:
    dependencies:
      emotion: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  form-data@*:
    dependencies:
      "@types/node": "*"
  glob-promise@*:
    dependencies:
      glob: "*"
  graphql-query-complexity@*:
    dependencies:
      graphql: "*"
  graphql-subscriptions@*:
    dependencies:
      "@types/node": "*"
  graphql-tag@*:
    peerDependencies:
      graphql: "*"
  graphql-toolkit@*:
    peerDependencies:
      graphql: "*"
  graphql-tools@*:
    peerDependencies:
      graphql: "*"
  merge-graphql-schemas@*:
    dependencies:
      graphql-tag-pluck: "*"
  mini-store@*:
    dependencies:
      react: "*"
  mqtt@*:
    dependencies:
      duplexify: "*"
  next-fonts@*:
    dependencies:
      webpack: "*"
  next-images@*:
    dependencies:
      webpack: "*"
  next@*:
    dependencies:
      "@types/node": "*"
      react-dom: "*"
  pg-cursor@*:
    dependencies:
      pg: "*"
  pino@*:
    dependencies:
      pino-pretty: "*"
  pretty-format@*:
    dependencies:
      "@types/pretty-format": "*"
  promise-inflight@*:
    dependencies:
      bluebird: "*"
  rc-align@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-collapse@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-select@*:
    dependencies:
      "@types/react": "*"
      react: "*"
      react-dom: "*"
  rc-trigger@*:
    dependencies:
      "@types/react": "*"
      react: "*"
      react-dom: "*"
  rc-util@*:
    dependencies:
      "@types/react": "*"
      react: "*"
      react-dom: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scrolllock@*:
    dependencies:
      "@types/react": "*"
  subscriptions-transport-ws@*:
    dependencies:
      "@types/node": "*"
  ts-morph@*:
    dependencies:
      source-map-support: "*"
  type-graphql@*:
    dependencies:
      class-validator: "*"
    peerDependencies:
      graphql: "*"
  typeorm@*:
    dependencies:
      pg: "*"
      pg-query-stream: "*"
      sqlite3: "*"
  typescript@*:
    dependencies:
      source-map-support: "*"
  webpack@*:
    dependencies:
      "@types/node": "*"
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"

yarnPath: .yarn/releases/yarn-0.0.1-git.20220304.hash-6afc8ff.cjs
