defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      '@grpc/grpc-js': '*'
      '@nestjs/websockets': '*'
      'amqp-connection-manager': '*'
      'amqplib': '*'
      '@nestjs/core': '*'
      '@nestjs/common': '*'
      'ioredis': '*'
      'kafkajs': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      '@nestjs/platform-socket.io': '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/common@*':
    dependencies:
      'class-transformer': '*'
      'class-validator': '*'
  'ws@8.17.1':
    dependencies:
      utf-8-validate: '5.0.2'
      bufferutil: '4.0.3'
  'debug@4.3.7':
    dependencies:
      supports-color: '9.4.0'
  'debug@4.4.0':
    dependencies:
      supports-color: '9.4.0'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
